---

- hosts: germes
  become: true
  gather_facts: yes

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    - role: system
    - role: geerlingguy.pip
    - role: geerlingguy.docker
      tags:
        - docker
    - role: prometheus.prometheus.node_exporter
    - role: geerlingguy.security
      tags:
        - security
    - role: docker
