---

all:
  hosts:
    children:
      home:

home:
  hosts:
    germes: # Your home server
      ansible_host: ''
      ansible_user: ''
      ansible_ssh_private_key_file: ''
      ansible_port: ''
    vpn: # Your VPN server
      ansible_host: ''
      ansible_user: ''
      ansible_port: ''
      ansible_ssh_private_key_file: ''
    gateway: # Your gateway server
      ansible_host: ''
      ansible_user: ''
      ansible_ssh_private_key_file: ''
      ansible_port: ''
